#!/usr/bin/env python3
from __future__ import annotations

import argparse
import csv
import os
import subprocess
import sys
from pathlib import Path


CONFIGS = [
    {
        "test_group": 1,
        "max_horizontal_distance": 90,
        "failure_rate": "0.10",
        "cycles": 4000,
        "grid_factor": 15,
    },
    {
        "test_group": 2,
        "max_horizontal_distance": 90,
        "failure_rate": "0.20",
        "cycles": 4000,
        "grid_factor": 15,
    },
    {
        "test_group": 3,
        "max_horizontal_distance": 110,
        "failure_rate": "0.10",
        "cycles": 6000,
        "grid_factor": 20,
    },
    {
        "test_group": 4,
        "max_horizontal_distance": 110,
        "failure_rate": "0.20",
        "cycles": 6000,
        "grid_factor": 20,
    },
    {
        "test_group": 5,
        "max_horizontal_distance": 130,
        "failure_rate": "0.10",
        "cycles": 8000,
        "grid_factor": 25,
    },
    {
        "test_group": 6,
        "max_horizontal_distance": 130,
        "failure_rate": "0.20",
        "cycles": 8000,
        "grid_factor": 25,
    },
]


def default_binary() -> Path:
    if os.name == "nt":
        return Path("bin") / "tsvra.exe"
    return Path("bin") / "tsvra"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Run six configurations and merge four result columns into one CSV file."
    )

    parser.add_argument(
        "--script",
        type=Path,
        default=Path("batch_experiment_method_mt.py"),
        help="Path to batch_experiment_method_mt.py.",
    )

    parser.add_argument(
        "--binary",
        type=Path,
        default=default_binary(),
        help="Path to TSVRA executable. Default: bin/tsvra.exe on Windows, bin/tsvra on Linux.",
    )

    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("output") / "threshold_calibration_short",
        help="Single output directory.",
    )

    parser.add_argument(
        "--output-csv",
        type=Path,
        default=None,
        help="Merged CSV output path. Default: <output-dir>/all_configs_summary.csv.",
    )

    parser.add_argument(
        "--jobs",
        type=int,
        default=None,
        help="Maximum number of concurrent simulator processes for each config.",
    )

    parser.add_argument(
        "--failure-mode",
        default="a",
        choices=["a", "b", "c"],
    )

    parser.add_argument(
        "--redundancy",
        default="shared",
        choices=["shared", "corner4", "none"],
    )

    parser.add_argument(
        "--failure-model",
        default="uniform",
        choices=["uniform", "clustered"],
    )

    parser.add_argument(
        "--layers",
        type=int,
        default=2,
    )

    parser.add_argument(
        "--start",
        type=int,
        default=1,
        help="Start test group id.",
    )

    parser.add_argument(
        "--end",
        type=int,
        default=6,
        help="End test group id.",
    )

    parser.add_argument(
        "--keep-intermediate",
        action="store_true",
        help="Keep experiment_method_summary.tsv/md generated by the inner script.",
    )

    return parser.parse_args()


def read_tsv_rows(path: Path) -> list[dict[str, str]]:
    with path.open("r", newline="", encoding="utf-8") as handle:
        reader = csv.DictReader(handle, delimiter="\t")
        return list(reader)


def write_merged_csv(path: Path, rows: list[dict[str, str]], fieldnames: list[str]) -> None:
    with path.open("w", newline="", encoding="utf-8-sig") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def main() -> int:
    args = parse_args()

    script = args.script
    binary = args.binary
    output_dir = args.output_dir
    output_csv = args.output_csv or output_dir / "all_configs_summary.csv"

    if not script.exists():
        print(f"ERROR: script not found: {script}", file=sys.stderr)
        return 1

    if not binary.exists():
        print(f"ERROR: binary not found: {binary}", file=sys.stderr)
        return 1

    output_dir.mkdir(parents=True, exist_ok=True)
    output_csv.parent.mkdir(parents=True, exist_ok=True)

    selected_configs = [
        config for config in CONFIGS
        if args.start <= config["test_group"] <= args.end
    ]

    if not selected_configs:
        print("ERROR: no configs selected.", file=sys.stderr)
        return 1

    # 最终 CSV 只保留这四列
    merged_fieldnames = [
        "总故障率",
        "阵列大小",
        "Horizontal Distance",
        "正确率",
    ]

    all_rows: list[dict[str, str]] = []

    for config in selected_configs:
        test_group = config["test_group"]

        print("=" * 80)
        print(f"Running test group {test_group}")
        print(f"max-horizontal-distance = {config['max_horizontal_distance']}")
        print(f"failure-rates           = {config['failure_rate']}")
        print(f"cycles                  = {config['cycles']}")
        print(f"grid-factor             = {config['grid_factor']}")
        print("=" * 80)

        cmd = [
            sys.executable,
            "-u",
            str(script),
            "--binary",
            str(binary),
            "--output-dir",
            str(output_dir),
            "--max-horizontal-distance",
            str(config["max_horizontal_distance"]),
            "--cycles",
            str(config["cycles"]),
            "--grid-factor",
            str(config["grid_factor"]),
            "--failure-mode",
            args.failure_mode,
            "--redundancy",
            args.redundancy,
            "--failure-model",
            args.failure_model,
            "--layers",
            str(args.layers),
            "--failure-rates",
            str(config["failure_rate"]),
        ]

        if args.jobs is not None:
            cmd.extend(["--jobs", str(args.jobs)])

        result = subprocess.run(cmd)

        if result.returncode != 0:
            print(f"ERROR: test group {test_group} failed.", file=sys.stderr)
            return result.returncode

        tsv_path = output_dir / "experiment_method_summary.tsv"
        md_path = output_dir / "experiment_method_summary.md"

        if not tsv_path.exists():
            print(f"ERROR: expected result file not found: {tsv_path}", file=sys.stderr)
            return 1

        rows = read_tsv_rows(tsv_path)

        if not rows:
            print(f"ERROR: no rows found in: {tsv_path}", file=sys.stderr)
            return 1

        for row in rows:
            all_rows.append(
                {
                    "总故障率": row.get("总故障率", ""),
                    "阵列大小": row.get("阵列大小", ""),
                    "Horizontal Distance": row.get("Horizontal Distance", ""),
                    "正确率": row.get("正确率", ""),
                }
            )

        # 每跑完一组就更新一次总 CSV，防止中途失败导致前面数据丢失
        write_merged_csv(output_csv, all_rows, merged_fieldnames)

        print(f"Updated merged CSV: {output_csv}")

        if not args.keep_intermediate:
            tsv_path.unlink(missing_ok=True)
            md_path.unlink(missing_ok=True)

    print("=" * 80)
    print("All selected test groups finished successfully.")
    print(f"Merged CSV saved to: {output_csv}")
    print("=" * 80)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())