package examples.poly

class Poly2CoreVerilatorConfig extends sims.verilator.BuckyballGoban2Tile1CoreVerilatorConfig

class Poly4CoreVerilatorConfig extends sims.verilator.BuckyballGoban4Tile1CoreVerilatorConfig

class Poly8CoreVerilatorConfig extends sims.verilator.BuckyballGoban8Tile1CoreVerilatorConfig

class Poly16CoreVerilatorConfig extends sims.verilator.BuckyballGoban16Tile1CoreVerilatorConfig

class Poly32CoreVerilatorConfig extends sims.verilator.BuckyballGoban32Tile1CoreVerilatorConfig

class Chipyard2CoreVerilatorConfig extends sims.verilator.Chipyard2CoreVerilatorConfig

class Chipyard4CoreVerilatorConfig extends sims.verilator.Chipyard4CoreVerilatorConfig

class Chipyard8CoreVerilatorConfig extends sims.verilator.Chipyard8CoreVerilatorConfig

class Chipyard16CoreVerilatorConfig extends sims.verilator.Chipyard16CoreVerilatorConfig

class Chipyard32CoreVerilatorConfig extends sims.verilator.Chipyard32CoreVerilatorConfig

class PolyChipC1Config extends sims.p2e.BuckyballGobanConfig1LinuxP2EConfig

class PolyChipC2Config extends sims.p2e.BuckyballGobanConfig2LinuxP2EConfig

class PolyChipC3Config extends sims.p2e.BuckyballGobanConfig3LinuxP2EConfig

class PolyChipC4Config extends sims.p2e.BuckyballGoban64Tile4CoreLinuxP2EConfig
