# Goban Tile (3 cores: core 0 has Buckyball, core 1 is Rocket-only, core 2 is safe core)

[privateDCache]
enable = true
ways = 4
capacityKB = 256
writeBytes = 8
portFactor = 2
memCycles = 10

[sharedMem]
enable = false
entries = 16384
inputChannels = 12
defaultGroupCount = 1
memCycles = 10

[[cores]]
include = "cores/default.toml"

[[cores]]
include = "cores/rocket.toml"

[[cores]]
include = "cores/safe-core.toml"
