# Goban Tile (4 cores: all cores have Buckyball)

[privateDCache]
enable = true
ways = 4
capacityKB = 256
writeBytes = 8
portFactor = 2
memCycles = 10

[sharedMem]
enable = false
entries = 16384
inputChannels = 4
defaultGroupCount = 1
memCycles = 10

[coreTemplate]
include = "cores/default.toml"
count = 4
