name: Buckyball CI (Push)
run-name: ${{ github.actor }} is running CI Test 🚀
on:
  push:
    branches:
      - main

jobs:
  CI-Test:
    name: CI Test
    runs-on: cpu-server
    env:
      ALL_PROXY: socks5h://127.0.0.1:7890
    steps:
      - name: Print information
        run: |
          echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
          echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      - name: Reset to clean state
        shell: zsh {0}
        run: |
          cd ~/Code/buckyball
          git fetch origin
          git clean -fd
          git checkout ${{ github.head_ref }}
          git pull
          git submodule update bbdev bebop compiler thirdparty/pegasus

      - name: Nix build
        shell: zsh {0}
        run: |
          cd ~/Code/buckyball
          nix build

      - name: Build Workloads
        shell: zsh {0}
        run: |
          cd ~/Code/buckyball
          nix develop -c bbdev workload --build

      - name: Build Verilator
        shell: zsh {0}
        run: |
          cd ~/Code/buckyball
          nix develop -c bbdev verilator --clean
          nix develop -c bbdev verilator --verilog '--config sims.verilator.BuckyballToyVerilatorConfig'
          nix develop -c bbdev verilator --build '--jobs 16'

      - name: Smoke Test
        shell: zsh {0}
        run: |
          cd ~/Code/buckyball
          nix develop -c bbdev sardine --run '--workload ctest' --dir arch/log

      # if check failed, revert the branch
      # - name: Revert Bad Commit
      #   if: failure()
      #   shell: zsh {0}
      #   run: |
      #     source ~/.zshrc
      #     buckyball_exec
      #     setproxy
      #     git reset --hard HEAD~1
      #     git push --force origin main
